baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Hesti Blog"
theme = "hesti"
themesdir = "../.."
enableRobotsTXT = true
summarylength = 10
canonifyURLs = true
paginate = 1
[params]
	image = "/images/hesti-header.jpg"
	thumbnail = "/assets/images/default-thumbnail.jpg"
[taxonomies]
	category = "categories"
[permalinks]
	categories = "/:slug/"