baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Hesti Blog"
theme = "hesti"
themesdir = "../.."
enableRobotsTXT = true
summarylength = 10
canonifyURLs = true
paginate = 1
[params]
	image = "/images/hesti-header.jpg"
	thumbnail = "/assets/images/default-thumbnail.jpg"
[taxonomies]
	category = "categories"
[permalinks]
	categories = "/:slug/"
[related]
	[[related.indices]]
		name  = "categories"
		weight = 80
	[[related.indices]]
		name  = "tags"
		weight = 100
[menu]
	[[menu.main]]
		identifier = "categories"
		name = "categories"
		url = "#"
		weight = 10
	[[menu.main]]
		parent = "categories"
		name = "Programming"
		url = "/programming/"
		weight = 10
	[[menu.main]]
		parent = "categories"
		name = "Statistics"
		url = "/statistics/"
		weight = 10