baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Hesti Blog"
theme = "hesti"
themesdir = "../.."
enableRobotsTXT = true
summarylength = 10
canonifyURLs = true
[params]
	image = "/images/hesti-header.jpg"